run:
  go: '1.19'
  timeout: 2m

issues:
  max-same-issues: 0
  exclude-rules:
    - text: "G112:"
      linters:
        - gosec

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - gocyclo
    - govet
    - gosec
    - ineffassign
    - staticcheck
    - stylecheck
    - unused