server:
  Port: :8000
  ReadTimeout: 5
  WriteTimeout: 5

postgres:
  PostgresqlHost: postgres
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: admin
  PostgresqlDbname: fizzbuzz
  PostgresqlSslmode: false
  PgDriver: pgx

metrics:
  Url: 0.0.0.0:8080
  ServiceName: api

jaeger:
  Host: api:6831
  ServiceName: fuzzbuzz
  LogSpans: false