server:
  port: :8000
  readTimeout: 5
  writeTimeout: 5

postgres:
  host: postgres
  port: 5432
  user: postgres
  password: admin
  dbname: fizzbuzz
  pgDriver: pgx

metrics:
  url: 0.0.0.0:8080
  serviceName: api

jaeger:
  host: http://jaeger:14268/api/traces
  serviceName: fizzbuzz