server:
  Port: :8000
  ReadTimeout: 5
  WriteTimeout: 5

postgres:
  Host: postgres
  Port: 5432
  User: postgres
  Password: admin
  Dbname: fizzbuzz
  PgDriver: pgx

metrics:
  Url: 0.0.0.0:8080
  ServiceName: api

jaeger:
  Host: api:6831
  ServiceName: fuzzbuzz