version: "3.8"
services:
 fizzbuzz-serve:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - GIN_MODE=release
    ports:
      - "${ENDPOINT_PORT:-8000}:8000"
    command: serve --port ":${ENDPOINT_PORT:-8000}" --timeout 100