version: "3.8"
services:
 fizzbuzz-serve:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - CONFIG=config.yaml
    ports:
      - "7070:7070"
      - "8000:8000"
    volumes:
      - ./config.yaml:/config.yaml