{
 "title": "Fizzbuzz",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"fizzbuzz\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "fizzbuzz_info_gauge ", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Built",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "fizzbuzz_info_gauge ", "legendFormat": "{{built}}" }
   ]
  },
  {
   "title": "Fizzbuzz number of requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fizzbuzz_hits{method=\"GET\",path=\"/api/v1/fizzbuzz\",status=\"200\"}"
    }
   ]
  },
  {
   "title": "Stats number of requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fizzbuzz_hits{method=\"GET\",path=\"/api/v1/stats\",status=\"200\"}"
    }
   ]
  },
  {
   "title": "Fizzbuzz responses time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "fizzbuzz_times_sum{method=\"GET\",path=\"/api/v1/fizzbuzz\",status=\"200\"}/fizzbuzz_times_count{method=\"GET\",path=\"/api/v1/fizzbuzz\",status=\"200\"}"
    }
   ]
  },
  {
   "title": "Stats response time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "fizzbuzz_times_sum{method=\"GET\",path=\"/api/v1/stats\",status=\"200\"}/fizzbuzz_times_count{method=\"GET\",path=\"/api/v1/stats\",status=\"200\"}"
    }
   ]
  }
 ]
}