basePath: /api/v1
definitions:
  domain.Statistics:
    properties:
      hits:
        type: integer
      int1:
        type: integer
      int2:
        type: integer
      limit:
        type: integer
      str1:
        type: string
      str2:
        type: string
    type: object
info:
  contact: {}
  description: Fizzbuzz REST API
  title: Go Fizzbuzz REST API
  version: "1.0"
paths:
  /fizzbuzz:
    get:
      consumes:
      - application/json
      description: 'Record request inside persistent repository and returns a list
        of strings with numbers from 1 to limit, where: all multiples of int1 are
        replaced by str1, all multiples of int2 are replaced by str2, all multiples
        of int1 and int2 are replaced by str1str2'
      parameters:
      - description: Integer1
        in: query
        name: int1
        required: true
        type: integer
      - description: Integer2
        in: query
        name: int2
        required: true
        type: integer
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: String1
        in: query
        name: str1
        required: true
        type: string
      - description: String2
        in: query
        name: str2
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Record and compute request
      tags:
      - Fizzbuzz
  /stats:
    get:
      description: Return the most used request, as well as the number of hits for
        this request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Statistics'
        "500":
          description: Internal Server Error
      summary: Process the most frequent request
      tags:
      - Fizzbuzz
swagger: "2.0"
